# ???????????? Git Pre-Commit Hooks
repos:
  # 1. ??????? ???????? ??????
  - repo: https://github.com/pre-commit/pre-commit-hooks #?????? ????? ????????
    rev: v4.6.0 #?? ??????
    hooks:
      - id: trailing-whitespace # ??????? ?????? ??????? ?? ?????? ?????
      - id: end-of-file-fixer # ??????????? ??????? ?????? ?????? ? ????? ?????
      - id: check-yaml # ????????? ?????????? ?????????? YAML-??????
      - id: check-added-large-files # ????????? ????? ?????? 5MB (????? ?? ??????????? ???? ???????)
        args: ["--maxkb=5000"]
      - id: check-merge-conflict # ????????? ?????????? ????????????? ???????? ?????????? Git

  # 2. ??????? ?????? ? ????????? Python (Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # ??????: ??????? ?????????????? ???????, ?????? ? ????????? ??????
      - id: ruff
        args: [--fix]
      # ?????????: ????????????? ??????????? ??? ??? ???????? (??? Black)
      - id: ruff-format
