dataset:
  kaggle_name: "backpacker/fasdd-flame-and-smoke-detection-dataset"
  raw_dir: "data/fasdd"
  summary_csv: "data/fasdd_parsed_summary.csv"
  # Наѝтройки режима ѝѝмплированиѝ
  sample_mode: true # true = брать только чаѝть данных, false = качать/копировать вѝё
  sample_limit: 500 # Количеѝтво файлов длѝ ѝѝмпла (еѝли sample_mode: true)

mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "FASDD_Dataset_Management_2"
  run_name: "dataset_eda_and_registration"

train:
  experiment_name: "fire_detection_dev"
  data_dir: "data/fasdd"
  epochs: 2
  batch: 4
  fraction: 0.02
  seed: 42
  registered_model_name: "fire-detector"
  dataset_name: "fire-detection-roboflow-v4" # надо поменѝть, ѝ брала урезанный датаѝет ѝ roboflow, а не целый ѝ kaggle
